import { Aws, Duration, RemovalPolicy, StackProps, CfnOutput } from 'aws-cdk-lib'
import { Construct } from 'constructs'
import * as s3 from 'aws-cdk-lib/aws-s3'
import { LogGroup, RetentionDays } from 'aws-cdk-lib/aws-logs'
import { PolicyStatement } from 'aws-cdk-lib/aws-iam'
import * as lambda from 'aws-cdk-lib/aws-lambda'
import { LambdaDestination } from 'aws-cdk-lib/aws-s3-notifications'
import { RestApi, LambdaIntegration, Cors, AuthorizationType} from 'aws-cdk-lib/aws-apigateway'
import * as path from 'path'

export interface ApiProps extends StackProps {
  account: string
  stage: string
  prefix: string
  knowledgeBaseFoundationModelArn: string
  knowledgeBaseBucketArn: string
  knowledgeBaseId: string
  knowledgeBaseArn: string
  collectionArn: string
  collectionId: string
  collectionName: string
  collectionEndpoint: string
  bedrockDataSourceId: string
}

export class Api extends Construct {
  constructor(scope: Construct, id: string, props: ApiProps) {
    super(scope, id);

    /**
     * This bucket contains the images generated by /generate-image Api
     */
    const assetsBucket = new s3.Bucket(this, `${props.prefix}-${props.account}-assets-${props.stage}`, {
      bucketName: `${props.prefix}-${props.account}-assets-${props.stage}`,
      cors: [{
        allowedMethods: [s3.HttpMethods.POST],
        allowedOrigins: ["*"],
        allowedHeaders: ["*"]
      }],
      removalPolicy: RemovalPolicy.DESTROY,
      publicReadAccess: false,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      autoDeleteObjects: true,
      lifecycleRules: [{
        enabled: true,
        expiration: Duration.days(1)
      }],
    })
    
    /**
     * API GW Defintion
     */
    const restApi = new RestApi(this, `${props.prefix}-bedrock-api-${props.stage}`, {
      restApiName: `${props.prefix}-bedrock-api-${props.stage}`,
      description: 'Sample Bedrock Http Api',
      deployOptions: {
        stageName: props.stage,
      },
      defaultCorsPreflightOptions: {
        allowOrigins: Cors.ALL_ORIGINS,
        allowHeaders: [
          'Content-Type',
          'X-Amz-Date',
          'Authorization',
          'X-Api-Key',
          'X-Amz-Security-Token',
          'X-Auth-Token',
          'Cognito-Refresh-Token',
          'User-Agent',
        ],
        allowMethods: ['OPTIONS', 'GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
        allowCredentials: true
      }
    })
    
    /**
     * API GW λ Function
     * This λ Function is used to ....
     */
    new LogGroup(this, `${props.prefix}-bedrock-request-log-grp-${props.stage}`, {
      logGroupName: `/aws/lambda/${props.prefix}-bedrock-request-${props.stage}`,
      retention: RetentionDays.ONE_YEAR,
      removalPolicy: RemovalPolicy.DESTROY,
    })
    const httpRequestLambdaFn = new lambda.Function(this, `${props.prefix}-bedrock-request-${props.stage}`, {
      functionName: `${props.prefix}-bedrock-request-${props.stage}`,
      runtime: lambda.Runtime.PYTHON_3_10,
      timeout: Duration.seconds(29),
      memorySize: 2048,
      handler: 'main.handler',
      environment: {
        STAGE: props.stage,
        API_URL: `https://${restApi.restApiId!}.execute-api.${Aws.REGION}.amazonaws.com/${props.stage}/`,
        ASSETS_BUCKET: assetsBucket.bucketName,
        DATA_SOURCE_ID: props.bedrockDataSourceId,
        KNOWLEDGE_BASE_ID: props.knowledgeBaseId,
        KNOWLEDGE_BASE_MODEL_ARN: props.knowledgeBaseFoundationModelArn,
      },
      code: lambda.Code.fromAsset(path.join(__dirname, '/../functions/py'), {
        bundling: {
          image: lambda.Runtime.PYTHON_3_10.bundlingImage,
          command: [
            'bash',
            '-c',
            'pip install -r requirements.txt -t /asset-output && cp -au . /asset-output',
          ],
        },
      }),
    })
    httpRequestLambdaFn.addToRolePolicy(new PolicyStatement({
      actions: [
        's3:GetObject',
        's3:PutObject',
        's3:HeadObject',
        's3:DeleteObject'
      ],
      resources: [
        `${assetsBucket.bucketArn}/*`,
      ]
    }))
    httpRequestLambdaFn.addToRolePolicy(new PolicyStatement({
      actions: [
        's3:ListBucket'
      ],
      resources: [
        `${assetsBucket.bucketArn}`,
      ]
    }))
    httpRequestLambdaFn.addToRolePolicy(new PolicyStatement({
      actions: [
        'bedrock:Invoke*',
        'bedrock:Retrieve*',
      ],
      resources: ['*']
    }))


    const kbBucket = s3.Bucket.fromBucketArn(this, `${props.prefix}-bedrock-Kb-bucket-arn-${props.stage}`, props.knowledgeBaseBucketArn)
    kbBucket.grantRead(httpRequestLambdaFn)

    kbBucket.addEventNotification(
      s3.EventType.OBJECT_CREATED, 
      new LambdaDestination(httpRequestLambdaFn),
      { prefix: 'knowledgeBase' },
    )
    
    /**
     * API GW Methods and Routes
     */
    restApi.root.addMethod('GET', new LambdaIntegration(httpRequestLambdaFn), {
      authorizationType: AuthorizationType.NONE
    })

    /**
     * Sample Foundation Models Endpoints
     * Llama 2 Chat 70B
     * Titan Image Generator G1
     * Cohere
     * Claude 3 Sonnet
     */
    restApi.root.addResource('generate-image').addMethod('POST', new LambdaIntegration(httpRequestLambdaFn))
    restApi.root.addResource('summarize-text').addMethod('POST', new LambdaIntegration(httpRequestLambdaFn))
    restApi.root.addResource('interpret-text').addMethod('POST', new LambdaIntegration(httpRequestLambdaFn))
    restApi.root.addResource('generate-code').addMethod('POST', new LambdaIntegration(httpRequestLambdaFn))

    /**
     * KnowledgeBase Query
     */
    restApi.root.addResource('knowledgebase-query').addMethod('POST', new LambdaIntegration(httpRequestLambdaFn))
  }
}